"""
Upload per-slide PNGs and caption txt files to Google Drive under Content/{date_slug}/.

Usage:
    uv run --with google-auth-oauthlib --with google-api-python-client \
        python scripts/upload_to_drive.py 2026-05-28

First run opens a browser for OAuth consent; token is cached in secrets/token.json.
Caption files (output/caption/{date}*_tiktok.txt and *_instagram.txt) are uploaded
automatically if they exist. Run /export-caption first to generate them.
"""

import sys
from pathlib import Path

SCOPES = ["https://www.googleapis.com/auth/drive"]
SECRETS_FILE = Path("secrets/vilamas-gcloud-secret.json")
TOKEN_FILE = Path("secrets/token.json")
CONTENT_FOLDER_ID = "1mqI8WY8TydWhAzn9BRtnlwxONI1PSDCw"


def get_credentials():
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
    from google_auth_oauthlib.flow import InstalledAppFlow

    creds = None
    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(str(SECRETS_FILE), SCOPES)
            creds = flow.run_local_server(port=0)
        TOKEN_FILE.write_text(creds.to_json())

    return creds


def find_or_create_folder(service, name, parent_id):
    query = (
        f"name='{name}' and mimeType='application/vnd.google-apps.folder'"
        f" and '{parent_id}' in parents and trashed=false"
    )
    results = service.files().list(q=query, fields="files(id,name)").execute()
    files = results.get("files", [])
    if files:
        return files[0]["id"]

    meta = {
        "name": name,
        "mimeType": "application/vnd.google-apps.folder",
        "parents": [parent_id],
    }
    folder = service.files().create(body=meta, fields="id").execute()
    return folder["id"]


def upload_file(service, path: Path, mimetype: str, parent_id: str):
    from googleapiclient.http import MediaFileUpload

    media = MediaFileUpload(str(path), mimetype=mimetype, resumable=True)
    meta = {"name": path.name, "parents": [parent_id]}
    # Overwrite if same name already exists
    query = f"name='{path.name}' and '{parent_id}' in parents and trashed=false"
    existing = service.files().list(q=query, fields="files(id)").execute().get("files", [])
    for f in existing:
        service.files().delete(fileId=f["id"]).execute()

    file = service.files().create(body=meta, media_body=media, fields="id,name,webViewLink").execute()
    return file


def main():
    if len(sys.argv) < 2:
        print("Usage: upload_to_drive.py YYYY-MM-DD")
        sys.exit(1)

    date_slug = sys.argv[1]
    images_dir = Path(f"output/images/{date_slug}")

    if not images_dir.exists():
        print(f"Error: {images_dir} not found. Run /pdf-to-images {date_slug} first.")
        sys.exit(1)

    slides = sorted(images_dir.glob("slide-*.png"))
    if not slides:
        print(f"Error: no slide-*.png files found in {images_dir}")
        sys.exit(1)

    from googleapiclient.discovery import build

    creds = get_credentials()
    service = build("drive", "v3", credentials=creds)

    folder_id = find_or_create_folder(service, date_slug, CONTENT_FOLDER_ID)
    print(f"Folder: Content/{date_slug}/ (id: {folder_id})")

    # Upload slides
    print("\nSlides:")
    for slide in slides:
        result = upload_file(service, slide, "image/png", folder_id)
        print(f"  {result['name']}  →  {result.get('webViewLink', result['id'])}")

    # Upload caption txt files (generated by /export-caption)
    caption_dir = Path("output/caption")
    caption_files = sorted(caption_dir.glob(f"{date_slug}*.txt")) if caption_dir.exists() else []
    if caption_files:
        print("\nCaptions:")
        for txt in caption_files:
            result = upload_file(service, txt, "text/plain", folder_id)
            print(f"  {result['name']}  →  {result.get('webViewLink', result['id'])}")
    else:
        print(f"\nCaptions: none found in output/caption/{date_slug}*.txt — run /export-caption first to include them.")

    total = len(slides) + len(caption_files)
    print(f"\nDone: {total} files uploaded to Content/{date_slug}/ ({len(slides)} slides, {len(caption_files)} captions)")


if __name__ == "__main__":
    main()
